update to 2.9.0.post0
AnacondaRecipes/python-dateutil-feedstock pull request #6
Opened 2024-05-22 16:27 UTC by cbouss

Re-update, because the previous version was fixed in the url.
Remove older patches and comments.

2024-05-22 19:37 UTC, JeanChristopheMorinPerso requested changes

2024-05-22 19:37 UTC, JeanChristopheMorinPerso commented on recipe/new_tzfile.patch
Umm, I think SF still want this file. Obiviously, this is only for their version and not the version on defaults.

2024-05-22 20:56 UTC, cbouss commented on recipe/new_tzfile.patch
I opened a ticket to track this. https://anaconda.atlassian.net/browse/PKG-4850
This PR is for our main channel though.

2024-05-23 15:11 UTC, JeanChristopheMorinPerso approved these changes
Approving, but the SF version will have to be sorted out quickly.

2024-05-23 15:15 UTC, Jrice1317 approved these changes

2024-05-23 17:20 UTC, merged

2024-06-30 21:14 UTC, kynan commented
@cbouss @JeanChristopheMorinPerso Could you please confirm why this is not a `noarch` build?

2024-07-02 13:52 UTC, JeanChristopheMorinPerso commented
@kynan We always build our packages this way. We partly do this because of how we build and test packages at Anaconda.

2024-07-02 16:56 UTC, danpetry commented
It was a policy decision made a while back, because there were too many edge cases with `python: noarch`, i.e. python packages not really being version-independent, which needed to be handled. We took the hit of having to build packages for each python version over the need to have all the edge cases, with specific version selectors, handled manually in the feedstocks.

2024-07-02 16:58 UTC, danpetry commented
Also, then they get built and tested explicitly on all python interpreter versions.

2024-07-02 20:41 UTC, kynan commented
Thanks for confirming. That rationale makes sense :)

2024-10-29 17:31 UTC, sam-s commented
I still observe the same problem after `conda install --force-reinstall python-dateutil` - files stamped with `2024-05-07`, `conda list python-dateutil` reports `2.9.0post0` while  `_version.py` has `2.8.2`

2024-10-29 23:06 UTC, danpetry commented
could you give a bit more info (eg output of `conda install --force-reinstall python-dateutil`, full build string of your python-dateutil package, whether you're using defaults or conda-forge?

2024-10-30 12:55 UTC, sam-s commented
> could you give a bit more info (eg output of `conda install --force-reinstall python-dateutil`, full build string of your python-dateutil package, whether you're using defaults or conda-forge?

How do I know _"whether I'm using defaults or conda-forge"_?

```
$ conda install --force-reinstall python-dateutil
Channels:
 - https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
 - https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
 - https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo
 - https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: $HOME\AppData\Local\miniconda3\envs\c312

  added / updated specs:
    - python-dateutil



Proceed ([y]/n)?


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ conda list --show-channel-urls dateutil
# packages in environment at $HOME\AppData\Local\miniconda3\envs\c312:
#
# Name                    Version                   Build  Channel
python-dateutil           2.9.0post0      py312haa95532_0    defaults
```

2024-10-30 22:51 UTC, danpetry commented
Thanks. can you try `conda install --force-reinstall python-dateutil --override-channels -c defaults`?

2024-10-31 13:32 UTC, sam-s commented
Thank you, this command did result in
```
$ conda list --show-channel-urls dateutil
# packages in environment at $HOME\AppData\Local\miniconda3\envs\c312:
#
# Name                    Version                   Build  Channel
python-dateutil           2.9.0post0      py312haa95532_2    defaults
```

2024-10-31 14:02 UTC, danpetry commented
You've also got other channels configured there. If you were to uninstall then reinstall, it would pick up one of your higher priority channels instead. I think the channel priority is interfering with `--force-reinstall`.

2024-10-31 14:03 UTC, danpetry commented
```
Channels:
 - https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
 - https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
 - https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo
 - https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
 - conda-forge
 - defaults
```

2024-10-31 23:02 UTC, sam-s commented
Both before and after `python-dateutil` was installed from `defaults` - how could the other channels affect the choice?

2024-11-05 23:38 UTC, danpetry commented
Hi @sam-s, apologies for the delay here.
This could be a bug in conda. I've opened a bug report [here](https://github.com/conda/conda/issues/14372). Do you have any further questions I can help with?

2024-11-06 17:46 UTC, danpetry commented
The behaviour of `--force-reinstall` should be the same as if you were to uninstall and then reinstall python-dateutils. This should result in a package from conda-forge instead of defaults, because you have conda-forge confiured as a higher-priority channel.